#consul服务端口号
server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
    #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     #当前数据源操作类型
    url: jdbc:mysql://localhost:3306/atguigu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false  #mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

