server:
  port: 7003
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-url: http://eureka7001.com:7001/eureka/
  instance:
    hostname: eureka7003.com
